# Matrix Algebra

In [2]:
import numpy as np

### Matrix Vector Multiplication

In [4]:
matrix_a = np.asarray([
    [0.7,3,9],
    [1.7,2,9],
    [0.7,9,2]], dtype=np.float32)

vector_b = np.asarray([
    [1],
    [2],
    [1]], dtype=np.float32)

In [5]:
ab_product =np.dot(matrix_a,vector_b)
ab_product

array([[15.7],
       [14.7],
       [20.7]], dtype=float32)

### Matrix Multiplication

In [6]:
matrix_a = np.asarray([
    [0.7, 3],
    [1.7, 2],
    [0.7, 9]
], dtype=np.float32)

matrix_b = np.asarray([
    [113, 3, 10],
    [1, 0, 1],
], dtype=np.float32)

In [7]:
product_ab = np.dot(matrix_a,matrix_b)
product_ab

array([[ 82.1      ,   2.1      ,  10.       ],
       [194.1      ,   5.1000004,  19.       ],
       [ 88.1      ,   2.1      ,  16.       ]], dtype=float32)

In [8]:
product_ba=np.dot(matrix_b,matrix_a)
product_ba

array([[ 91.2, 435. ],
       [  1.4,  12. ]], dtype=float32)

### Matrix Transpose

In [14]:
matrix_a = np.asarray([
    [0.7, 3],
    [1.7, 2],
    [0.7, 9]], dtype=np.float32)

matrix_b = np.asarray([
    [113, 3, 10],
    [1, 0, 1],
], dtype=np.float32)

In [15]:
transpose_a = np.transpose(matrix_a)
transpose_a

array([[0.7, 1.7, 0.7],
       [3. , 2. , 9. ]], dtype=float32)

In [16]:
np.transpose(transpose_a)

array([[0.7, 3. ],
       [1.7, 2. ],
       [0.7, 9. ]], dtype=float32)

In [17]:
trans_ba = np.dot(np.transpose(matrix_b),np.transpose(matrix_a))
trans_ba

array([[ 82.1      , 194.1      ,  88.1      ],
       [  2.1      ,   5.1000004,   2.1      ],
       [ 10.       ,  19.       ,  16.       ]], dtype=float32)

In [18]:
trans_ab=np.dot(np.transpose(matrix_a),np.transpose(matrix_b))
trans_ab

array([[ 91.2,   1.4],
       [435. ,  12. ]], dtype=float32)

In [20]:
product_ab = np.dot(matrix_a,matrix_b)
product_ab

array([[ 82.1      ,   2.1      ,  10.       ],
       [194.1      ,   5.1000004,  19.       ],
       [ 88.1      ,   2.1      ,  16.       ]], dtype=float32)

### Identity Matrix

In [21]:
i_2 = np.identity(2)
i_3 = np.identity(3)
print(i_2)
print(i_3)

[[1. 0.]
 [0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [22]:
matrix_23 = np.asarray([
    [0.7, 3, 1],
    [1.7, 2, 10],
], dtype=np.float32)

matrix_33 = np.asarray([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [23]:
identity_23 = np.dot(i_2, matrix_23)
identity_23

array([[ 0.69999999,  3.        ,  1.        ],
       [ 1.70000005,  2.        , 10.        ]])

In [24]:
identity_33 = np.dot(i_3, matrix_33)
identity_33

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

### Matrix Inverse

In [32]:
def matrix_inverse_two(M):
    det_M = (M[0,0]*M[1,1] - M[0,1]*M[1,0])
    if det_M == 0:
        raise ValueError("This matrix is not invertible!")
    return np.dot(1/det_M,np.asarray([[M[1,1], -M[0,1]],[-M[1,0], M[0,0]]]))

In [35]:
# matrix_inverse_two(np.asarray([[1,0],[0,0]]))

In [36]:
matrix_a = np.asarray([
    [1.5, 3],
    [1, 4]])

inverse_a = matrix_inverse_two(matrix_a)
inverse_a

array([[ 1.33333333, -1.        ],
       [-0.33333333,  0.5       ]])

In [37]:
np.dot(inverse_a, matrix_a)

array([[1., 0.],
       [0., 1.]])

### Solving the Matrix Equation

In [38]:
matrix_a = np.asarray([
    [30, -1],
    [50, -1]
])

vector_b = np.asarray([
    [-1000],
    [-100]
])

In [39]:
a_inverse = np.linalg.inv(matrix_a)
a_inverse

array([[-0.05,  0.05],
       [-2.5 ,  1.5 ]])

In [40]:
solution_x = np.dot(a_inverse, vector_b)
solution_x

array([[  45.],
       [2350.]])

### Determinant of matrices with higher dimensions

In [41]:
matrix_22 = np.asarray([
    [8, 4],
    [4, 2]
])


det_22 = np.linalg.det(matrix_22)
det_22

0.0

In [42]:
matrix_33 = np.asarray([
    [1, 1, 1],
    [1, 1, 6],
    [7, 8, 9]
])

det_33 = np.linalg.det(matrix_33)
det_33

-4.999999999999997

### Inverse of matrices with higher dimensions

In [45]:
matrix_33 = np.asarray([
    [1, 1, 1],
    [1, 1, 6],
    [7, 8, 9]
])

np.linalg.inv(matrix_33)

array([[ 7.8,  0.2, -1. ],
       [-6.6, -0.4,  1. ],
       [-0.2,  0.2, -0. ]])